package com.jswone.orchestrator.dto.enums;

public enum ResponseErrorCodes {
  MULTIPLE_REQUEST_RECEIVED,
  ORDER_CREATION_ERROR,

  NO_CUSTOMER_FOUND_ERROR,

  INTERNAL_SERVER_ERROR,

  ORDER_PAYMENT_FETCH_ERROR,
  PAYMENT_SUMMARY_FETCH_ERROR,

  ORDER_SUMMARY_FETCH_ERROR,
  CREATE_PAYMENT_ERROR,

  RAZORPAY_PAYMENT_UPDATE_ERROR,

  OPEN_ORDER_FETCH_BY_OPPORTUNITY,

  ORDER_ALREADY_PRESENT_FOR_OPPORTUNITY,

  CUSTOMER_CREDIT_NOT_FOUND,

  CUSTOMER_CREDIT_FETCH_ERROR,

  FETCH_ORDER_BLOCK_DETAILS_ERROR,

  DASHBOARD_ORDER_STATE_NOT_FOUND,

  BAD_REQUEST,
  SHIPMENT_ID_IS_MISSING,
  FILE_NOT_FOUND,
  DELIVERY_DATE_IS_NULL_OR_EMPTY,
  SHIPMENT_STATE_IS_NOT_DISPATCHED,
  FILE_IS_EMPTY,
  FILE_ORIGINAL_NAME_ISEMPTY,
  INVALID_FILE
}
