spring:
  config:
    import: classpath:external-apis.yml
  profiles:
    active:  ${PROFILE}
  application:
    name: due-notification-workflow
server:
  port: 8746
  servlet:
    context-path: /due-notification-workflow
http:
  connection:
    read-timeout: 50000
    server-connect-timeout: 2000





