spring:
  cloud:
    gcp:
      project-id: ${GCP-PROJECT-ID:jswone-qa-356112}
      pubsub:
        orchestrator-to-notification: ${NOTIFICATION-PUBSUB-TOPIC:notification-request-queue}
  datasource:
    url: jdbc:postgresql://${ORCHESTRATOR-DB-IP}:5432/orchestrator
    username: ${ORCHESTRATOR-DB-USERNAME}
    password: ${ORCHESTRATOR-DB-PWD}
    driver:
      class:
        name: org.postgresql.Driver
temporal:
  server-base-url: ${TEMPORAL-BASE-URL:}
  namespace: ${TEMPORAL-NAMESPACE:due-payments-notification}
  due-notification-task-queue: ${DUE-NOTIFICATION-QUEUE:due-notification-task-queue}

external-service:
  ledger:
    base-url: ${LEDGER-BASE-URL:http://localhost:8881/}
    client-user: ${LEDGER-SERVICE-CLIENT-USER:LSCLI4}
    client-secret: ${LEDGER-SERVICE-SECRET:LedgerService.SF.$2a$12$BAkN3bUGsEv2X354pwQkHOWBfUPH/taQWkigtp7pWm4QFJvco3dae}
  joms:
    base-url: ${JOMS-BASE-URL:https://qa-oms.msme.jswone.in/joms/api}
    api-key:  ${JOMS-API-KEY:3f9a2b5f-7bd8-4a51-b11f-47b30decd925}

notification:
  report-to-email: ${REPORT-TO-EMAIL:nitish.rohilla@jsw.in}
  report-cc-email: ${REPORT-CC-EMAIL:nitish.rohilla@jsw.in}

