spring:
  cloud:
    gcp:
      project-id: ${GCP-PROJECT-ID:modular-bucksaw-305821}
      pubsub:
        orchestrator-to-notification: ${NOTIFICATION-PUBSUB-TOPIC}

temporal:
  server-base-url: ${TEMPORAL-BASE-URL}
  namespace: ${TEMPORAL-NAMESPACE}
  pre-do-allotment-task-queue: ${FG-PRE-DO-ALLOTMENT-QUEUE:fg-pre-do-allotment-task-queue}
  schedules:
    pre-do-allotment-cron: ${PRE-DO-ALLOTMENT-CRON:0 0 * * *}

external-service:
  joms:
    base-url: ${JOMS-BASE-URL}
    api-key:  ${JOMS-API-KEY}


