spring:
  config:
    import: classpath:external-apis.yml
  profiles:
    active:  ${PROFILE}
  application:
    name: order-release
server:
  port: 8080
  servlet:
    context-path: /order-release
http:
  connection:
    read-timeout: 50000
    server-connect-timeout: 2000





